### ISSUE TITLE
Is anyone thinking about a new tag (1.20)?

### ISSUE THREAD

**Issue by galmasi** [theopolis/uefi-firmware-parser#107]
We have been using uefi-firmware-parser to deal with a number of firmwares over the last year or so, and it would be nice to have the latest. I have recently set up a travis job involving uefi-firmware-parser-1.9 and ran into NVAR related problem, fixed I think sometime last year. 

Just nicely asking to please consider posting the latest to pypy. Many thanks!

**Comment by theopolis** [comment]
Done, 1.9 should be built from the tip just now.
