### ISSUE TITLE
Latest Version Not On PyPi

### ISSUE THREAD

**Issue by EmperorArthur** [theopolis/uefi-firmware-parser#114]
V1.9 Was released on September 13.

However, the v1.9 in PyPi was released on May 19, 2020.  The exact same date as v1.8!

This means the fixes which allow the code to run with Python3 are not there!

**Comment by akshatmishra1203** [comment]
What's the problem.

**Comment by theopolis** [comment]
I will try to work on this soon. The issue is that my old workflow of building and uploading is not valid anymore as now PyPi needs universal builds (which makes sense).
