### ISSUE TITLE
Parser does not process compressed PE32 images

### ISSUE THREAD

**Issue by yeggor** [theopolis/uefi-firmware-parser#123]
The parser does not take into account the case where we have `File -> GUID Defined Section -> PE32 image/UI`.

The screenshot below shows an example of valid parsing by UEFITool:

<img width="977" alt="image" src="https://github.com/theopolis/uefi-firmware-parser/assets/22826617/17f86caa-281c-4adf-a2d5-312ccc11406c">

If we run `uefi-firmware-parser` on the test file in verbose mode (`uefi-firmware-parser -b --verbose Volume_FFSv2_5C60F367-A505-419A-859E-2A4FF6CA6FE5.vol`), we get the following result: [log.txt](https://github.com/theopolis/uefi-firmware-parser/files/14120558/log.txt).

As far as I can see, it successfully performs the decompression, but it does not process the data with respect to parent file.

The test volume is attached:
[Volume_FFSv2_5C60F367-A505-419A-859E-2A4FF6CA6FE5.vol.zip](https://github.com/theopolis/uefi-firmware-parser/files/14118174/Volume_FFSv2_5C60F367-A505-419A-859E-2A4FF6CA6FE5.vol.zip)

**Comment by NikolajSchlej** [comment]
Can you elaborate on what is the issue exactly? What do you expect to be processed and how?

**Comment by yeggor** [comment]
It's probably not clear from my description, but I gave a screenshot from uefitool as an example of valid parsing.

Whereas if we run `uefi-firmware-parser` on the test volume, it will be parsed, but none of the PE images will be extracted.

Here is the log for `uefi-firmware-parser -b --verbose ../fwhunt-scan/test/Volume_FFSv2_5C60F367-A505-419A-859E-2A4FF6CA6FE5.vol`:

[log.txt](https://github.com/theopolis/uefi-firmware-parser/files/14120510/log.txt)
