### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by kupiakos** [theopolis/uefi-firmware-parser#19]
Is Python 3 support planned for this project? It didn't successfully build on Python 3.

**Comment by theopolis** [comment]
I wasn't planned. But if python 3 would be useful for you I can try this week. Is there 3-only code (or a specific project) you'd like to integrate with?

**Comment by kupiakos** [comment]
I'm researching what sorts of frameworks to use for an OS-deployment project, and manipulating UEFI properly is a pretty important part of it. Nothing specific yet. I'm developing it "for the future" so I'm strictly keeping it on Python 3.

I was also planning on using it for basic deployment scripts, but I don't want to overburden you if Python 3 support would be too difficult.

**Comment by theopolis** [comment]
Cool! Shouldn't take too long, let me get back to you tonight.

**Comment by theopolis** [comment]
Going to take some time getting the bytes/unicode/str types straight but it's getting there (#22).

**Comment by kupiakos** [comment]
The library [Six](https://pythonhosted.org/six/) might help, depending on how complicated it is.

**Comment by theopolis** [comment]
Generally finished for the `uefi_firmware` module, some of the scripts still use Python 2 APIs.
