### ISSUE TITLE
AttributeError when parsing PFS files

### ISSUE THREAD

**Issue by insomniacslk** [theopolis/uefi-firmware-parser#60]
Thanks for the amazing tool :-)
I've run `uefi-firmware-parser` against a PFS dump of a Dell BIOS and got an `AttributeError`. The relevant, ending part of the stack trace is:

```
  File "build/bdist.linux-x86_64/egg/uefi_firmware/pfs.py", line 420, in showinfo
  File "build/bdist.linux-x86_64/egg/uefi_firmware/pfs.py", line 317, in showinfo
AttributeError: 'PFSSection' object has no attribute 'ts'
```

This is in the `PFSSection.showinfo()` method. The attributes `self.ts` and `self.type` are not set. I've looked elsewhere in the code but it's not immediate to me where/how these attributes should be populated. If I remove those two attributes from being printed, everything goes through fine.

Let me know if you need any further information, and thanks for any help here :-)

**Comment by theopolis** [comment]
It looks like this was fixed with https://github.com/theopolis/uefi-firmware-parser/pull/64/files

**Comment by insomniacslk** [comment]
Thanks!
