### ISSUE TITLE
No files were generated after the instruction was executed‘uefi-firmware-parser -O rom.binrom.bin’

### ISSUE THREAD

**Issue by RockySYR** [theopolis/uefi-firmware-parser#90]
#If you need to parse and extract a large number of firmware files check out the -O option to auto-generate an output folder per file.#

I met a problem，No files were generated after the instruction was executed

**Comment by theopolis** [comment]
See the issue here: https://github.com/theopolis/uefi-firmware-parser/issues/89

**Comment by zhjygit** [comment]
> See the issue here: #89

Nothing in #89.
#89 is also nothing.

**Comment by philmb3487** [comment]
Doesn't work here, empty folder
