### ISSUE TITLE
How to parse fd type firmware files

### ISSUE THREAD

**Issue by RockySYR** [theopolis/uefi-firmware-parser#91]
Can uefi-firmware-parser parse fd type firmware files？

**Comment by theopolis** [comment]
I think it should, try `uefi-firmware-parser -b FILENAME` and if that does not work try `uefi-firmware-parser --superbrute FILENAME`, these may take a while to run and may use a lot of memory.

**Comment by JohnAZoidberg** [comment]
Yes it does. Even without `-b`.
