### ISSUE TITLE
File-not-exist failures are not evident

### ISSUE THREAD

**Issue by MikeSpreitzer** [theopolis/uefi-firmware-parser#98]
As can be seen at https://github.com/theopolis/uefi-firmware-parser/blob/2af7e41c800300b0509494cec1db7125d2be2de9/bin/uefi-firmware-parser#L142 , in case a given file does not exist, the program does not terminate a non-zero exit code.  That makes it tough to use carefully from a higher level shell script or program.

**Comment by theopolis** [comment]
Good find, do you mind submitting a PR with a fix?
